version: "3.9"

services:
  
  frontend:
    build:
      context: ../ 
      dockerfile: srcs/frontend/Dockerfile
    container_name: frontend
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - .env
    networks:
      - transcendence
    image: frontend:trans
    restart: unless-stopped
    expose:
      - "3000"

  backend:
    build:
      context: ../
      dockerfile: srcs/backend/Dockerfile
    container_name: backend
    volumes:
      - ./server:/var/www/backend
      - /var/www/backend/node_modules
    env_file:
      - .env
    networks:
      - transcendence
    image: backend:trans
    restart: unless-stopped
    expose:
      - "4000"

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "443:443"
    depends_on:
      - frontend
      - backend
    volumes:
      - ./nginx/conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - transcendence
    image: nginx:trans
    restart: unless-stopped


networks:
  transcendence:
    name: transcendence
