import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Topheader from "./components/topheader";
import Leftheader from "./components/leftheader";

import { console } from "inspector";
import { Chakra_Petch } from "next/font/google";
import { LayoutComp } from "./components/layoutnavbar";

const chakra = Chakra_Petch({
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  variable: "--font-chakra",
});


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className="font-chakra h-screen" >

        <img
          src="/back.webp"
          alt="Logo"
          className="absolute w-full h-full object-cover -z-10"
          style={{ filter: "brightness(0.5) blur(8px)" }}
        />
        {/* Ensure children is rendered */}
        <LayoutComp>{children}</LayoutComp>
      </body>
    </html>
  );
}
