import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Topheader from "./components/topheader";
import Leftheader from "./components/leftheader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <img
          src="/back.webp"
          alt="Logo"
          className="absolute w-full h-full object-cover -z-10"
          style={{ filter: "brightness(0.5) blur(8px)" }}
          width={1000}
          height={1000}
        />
        <div className="flex h-screen z-0 relative">
          <Leftheader  />
          <div className="flex flex-1 flex-col z-10">
            <Topheader />
            <main className="flex-1 p-4 overflow-y-auto border-l-[0.5px] border-t-[0.5px] rounded-tl-xl">
              {children}
            </main>
          </div>
        </div>
      </body>
    </html>
  );
}